version: 0.0
os: linux
files:
  - source: /app
    destination: /var/www/html
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  ApplicationStop:
    - location: scripts/ApplicationStop.sh
      timeout: 30
      runas: ec2-user
  BeforeInstall:
    - location: scripts/BeforeInstall.sh
      timeout: 30
      runas: ec2-user
  AfterInstall:
    - location: scripts/AfterInstall.sh
      timeout: 30
      runas: ec2-user
  ApplicationStart:
    - location: scripts/ApplicationStart.sh
      timeout: 30
      runas: ec2-user
